### ISSUE TITLE
Feature Req: Real time preview

### ISSUE THREAD

**Issue by Tomasu** [facebook/litho#157]
Not a bug, but I find real time preview in IDEs very helpful, so something that worked in Android Studio with Litho would be very cool.

**Comment by pavlospt** [comment]
Supposedly that someone could include a webview or electron thing on an IntelliJ plugin, this could seem possible, with the Stetho integration.

**Comment by shalva97** [comment]
any update on this?

**Comment by pavlospt** [comment]
@shalva97 please check https://github.com/facebook/flipper

**Comment by colriot** [comment]
Thanks @pavlospt !
@shalva97 specifically the Layout plugin, which can show you the Components Hierarchy from the phone into Flipper window. And you can even tweak some of Components props to check the UI changes in realtime.

Android Studio Preview is smth that we are planning to experiment, but it's a lot harder to implement due to Yoga native lib dependency
