### ISSUE TITLE
what's the relationship between litho and React Native for Android

### ISSUE THREAD

**Issue by Shuijwan** [facebook/litho#190]
Litho is released in F8 2017, and is a great UI framework. according to the document, it has several great features like layout in background thread, incremental mount to improve the performance.  and some of the technical are same as React native. The question is why not just merge these features to React native for android and reinvent another wheel? are there some consideration? what's the relationship between litho and RN for android? I am confused at which one to choose.

**Comment by emilsjolander** [comment]
Great Questions! Both React Native and Litho take a lot of learning from React.js which is why there are a lot of similarities. While they are similar in many ways Litho also differs from React Native in many ways, one obvious one is the choice of language. At Facebook we have seen a lot of value in both frameworks and depending on the project, surface, and team makeup one framework is better than the other. We don't see either framework competing with the other but instead complementing each other. I suggest you and anyone else wondering about which to use try out both and use the one that you feel fits your current project and team best.

**Comment by IgorGanapolsky** [comment]
@emilsjolander I too am wondering - what do you mean by 
> complementing each other

Is there a sample of how to effectively use both in production?
