### ISSUE TITLE
RecyclerBinder has private access

### ISSUE THREAD

**Issue by hussainahmad** [facebook/litho#218]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
`V:0.5.0`

## Issues and Steps to Reproduce
My code running fine but when I updated to latest version which is `0.5.0`  then getting error 
```Error:(89, 26) error: constructor RecyclerBinder in class RecyclerBinder cannot be applied to given types;
required: Builder
found: ComponentContext,GridLayoutInfo
reason: actual and formal argument lists differ in length``` 

![recyclerbinder](https://user-images.githubusercontent.com/5903522/28870394-8d94557a-7799-11e7-9808-6338063a5ce4.png)

**Comment by hussainahmad** [comment]
[https://user-images.githubusercontent.com/5903522/28870394-8d94557a-7799-11e7-9808-6338063a5ce4.png](recyclerbinder)

**Comment by mihaelao** [comment]
Hey @hussainahmad, we made the RecyclerBinder constructor private and exposed a Builder instead because it was getting ugly maintaining all the different constructors when we wanted to add a new param. Check out this commit: https://github.com/facebook/litho/commit/19ce14e31a66662de472f94d2a9abe70e86b1a66

Hope that helps.

**Comment by hussainahmad** [comment]
Sorry, i didn't notice this, I updated from `V:0.3.1` to `0.5.0` BTW thanks
