### ISSUE TITLE
Setting a component causes runtime crash related to Yoga JNI

### ISSUE THREAD

**Issue by dsyang** [facebook/litho#273]
When I try to add litho to another app, it crashes with a JNI error related to Yoga:

`Failed to register native method com.facebook.yoga.YogaNode.jni_YGNodeFree(J)V`

Full trace from `adb logcat`: https://gist.github.com/dsyang/e1f32c9d333307020d4cc35428167169

- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
Using litho 0.8.0. Tried  0.7.1 but still got the error

## Issues and Steps to Reproduce
clone https://github.com/dsyang/android-architecture/tree/todo-litho
- build the app
- launch it
Observe crash

## Expected Behavior
it shouldn't crash 

## Link to Code
https://github.com/dsyang/android-architecture/tree/todo-litho

**Comment by passy** [comment]
That's strange. Thanks for the repo with the repro code, I'll look into this in more detail tomorrow. I wonder if this could be because we rely on a slightly outdated version of Yoga now. Perhaps overriding this to work with a Yoga snapshot release would work as temporary fix until we have a new stable release out.

**Comment by passy** [comment]
This is really weird. So, I've tried to force this to use a Yoga snapshot, but that doesn't change a thing. I've now tried to build our sample app against the prod artifacts like you've done in your project and it continues to work just fine.

I get the feeling that this has something to do with the way the app is set up. I'm honestly not quite sure what the mock and prod flavor do and how the whole `Injection` business works, but something is clearly interfering with the way we load Yoga.

A random guess that I can't verify easily right now is that this has to do with multidex. The JNI mapping mechanism may not be able to look up symbols that aren't part of the primary dex. As far as I can tell, this app has 6 dexes at the moment.

**Comment by passy** [comment]
Nope. I was thinking too complicated. Just turn `minifyEnabled` to `false` and everything is fine.

![screenshot 2017-11-13 11 02 50](https://user-images.githubusercontent.com/9906/32722595-47605e72-c862-11e7-9db5-440de2f41e30.png)

Turns out the APK doesn't even have a `com.facebook` namespace in it. Even in the debug build:

![screenshot 2017-11-13 11 05 11](https://user-images.githubusercontent.com/9906/32722670-8762f39a-c862-11e7-9e50-eeff80b30a2d.png)

You can also add a `-keep class com.facebook.** { *; }` rule to your proguard config, or something more specific, of course.
