### ISSUE TITLE
Add support for Text.Builder.extraSpacingSp(float sp)

### ISSUE THREAD

**Issue by vinc3m1** [facebook/litho#281]
Currently the extraSpacing value on Text doesn't support Sp.

Would open a PR, but CLA approvals and such 😢

**Comment by pavlospt** [comment]
From what I see only one line would be needed in order to generate `extraSpacingSp` as a *very* quick solution. 

`BuilderGenerator.java` L:421

```java
dataHolder.addTypeSpecDataHolder(sipBuilders(specModel, prop, requiredIndex));
```

Although that would generate `*Sp` methods for other attributes as well, so I am not quite sure how ok the Litho team is with it. 

The way I see a better solution is to add another `ResType` like: `DIMEN_OFFSET_FOR_SP` and only generate `*Sp` methods for this one, or a more appropriate which is to enrich `Prop` annotation with a method for the Props that the user would require `*Sp` methods for, on `Spec.Builder`.

LMK what you think. I can prepare a PR for either of those, I guess :)

cc: @passy @pasqualeanatriello

**Comment by IanChilds** [comment]
Hi @vinc3m1, @pavlospt! @pavlospt, I think your quick solution would be fine - thanks!

**Comment by pavlospt** [comment]
@IanChilds Hey, thanks for the reply! If it makes sense to generate it for the rest of the attributes though let me know and I can open a PR :)

**Comment by pavlospt** [comment]
Opened the above PR for it! :)

**Comment by pavlospt** [comment]
@passy or @IanChilds you can close this one as well :)

**Comment by vinc3m1** [comment]
I trust ya'll. I'll reopen if this is still an issue after next release.
