### ISSUE TITLE
Using DataDiffSection for heterogeneous data

### ISSUE THREAD

**Issue by bradroid** [facebook/litho#288]
I have a large RecyclerView with lot of different view types and would like to migrate to Litho. I have some views which are quite hard to migrate:

- item with graph range picker (implemented as custom android view)
- item which uses youtube SDK for youtube video
- item which provides picking a location using google maps
- item which uses TextInputLayout for floating label effect

So due to migration difficulties with these views, I would like to keep their implementation using Android framework. There are a lot of other items in my scrollable surface which can be migrated to Litho, so I would like to use a mix of components and android views for my Section.

Documentation: "View support is only offered by DataDiffSection at the moment."
Me: Great, I will try to use DataDiffSection, lets check what that is...
Documentation: "A DataDiffSection is used to represent a homogeneous list of data."
Me: Homogeneous?? But my list is quite heterogeneous. Not sure if I can still use this thing for my use case.

Question: What does the "homogeneous" really mean for DataDiffSection? Maybe it's related to models - do models need to be of the same type, but views can still be different?

**Comment by passy** [comment]
cc @mihaelao @pasqualeanatriello

**Comment by mihaelao** [comment]
Hey @bradroid, the "homogeneous" term refers to the type of data contained by the list that is passed to the DataDiffSection to render. I think it's a bit misleading since you could simply pass a list of `Object` items that can be of different actual types, do `instanceof` checks in the `RenderEvent ` handler and render the data with the appropriate component for its type. However, when your items change and the DataDiffSection needs to render new data, the diffing algorithm will do comparisons between the previous and current data so it has to work under the assumption that items are of the same type in order to be able to compare them.
That's to say that you can always work with the most generic type if your data is heterogeneous  but diffing won't be as efficient.

**Comment by bradroid** [comment]
Thanks!

**Comment by passy** [comment]
Closing as this appears to be answered. :)
