### ISSUE TITLE
@OnUpdateState unable to read ComponentContext 

### ISSUE THREAD

**Issue by caiiiycuk** [facebook/litho#627]
Hi. 
This is something that I don't understand in litho. Why I can't pass component context to `@OnUpdateState` method. When I try to do this and I have an exception that it's prohibited.
I need it to send events when state is updated. Even more it's weird becasue when I add `@Param ComponentContext c` I have an error:
 ```
 error: variable c is already defined in method updateSync(ComponentContext,ComponentContext)
  protected static void updateSync(ComponentContext c, ComponentContext c) {
```

So, it's passed anyway but if I want to use it, then I need to pass new param `ComponentContext componentContext`. This is strange, why it works in that way?

**Comment by colriot** [comment]
Hi there! First of all you need to differentiate between a method that triggers a State update (that is generated) and the closure that really updates the value (what you define). `c` that is passed to a generated method is used to trigger a State update. For a closure that calculates the new state it is usually no need of ComponentContext, because if it will be capturing the possibly old value of a `ComponentContext` (as this closure can be executed asynchronously). It's generally not good, but for the case like yours (for EventDispatching it's ok, as info used to retrieve a correct EventDispatcher should not change. In this case we recommend to simply pass `ComponentContext` as a `@Param` as __you've done__, but with the name different from `c`.

**Comment by caiiiycuk** [comment]
Thanks.
