### ISSUE TITLE
[Question] how to use for grow weights inside ConstraintLayout

### ISSUE THREAD

**Issue by xirdneh** [facebook/litho#698]
I am using a ConstraitLayout in my main activity with a drawer navigation. In my navigation fragment I'm using a RecyclerCollection to render a list of cards.
The card itself has a maxHeight set and I'm trying to set different weights for each row inside the layout spec.
I've tried using different weights but it doesn't seem to work, the only way I can get it to work is by actually setting a height to each of the rows inside the card layout.
What is the correct way of using flexGrow weight in this case?
Thanks!

**Comment by andrewpmsmith** [comment]
You should be setting the size directly on each row (or allowing it to be calculated from the contents) in a RecyclerCollection, rather than using flexGrow. It doesn't make sense to use flex grow inside a RecyclerView as the scroll area doesn't have a restricted height for the component to grow into.
If you want to use flexGrow to space your items then you can put them inside a Column/Row.

**Comment by xirdneh** [comment]
@andrewpmsmith That last sentence is what I was missing. I thought flex/grow would work on any component.
I had something like this:
```kotlin
@OnCreateLahyout
fun onCreateLayout(c: ComponentLayout) : Component {
    return Card.create(c)
        .child(
            Column.create(c).flexGrow(1F)
                .child(Text.create(c).text("Some text").flexGrow(1F).build())
                .child(SolidColor.create(c).color(Color.GRAY).flexGrow(2F).build())
        .heightDip(368F)
        .flexGrow(1F)
        .build()
}
```
The fix was to move `.heightDip(368F)` from the `Card` component to the inner `Column` component.
Everything else about being inside a ConstraintLayout and a Recycler View doesn't really matter.
Thanks!
