### ISSUE TITLE
LithoView does not respect margins

### ISSUE THREAD

**Issue by hipczor** [facebook/litho#699]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.32.0

## Issues and Steps to Reproduce
Setting margins on the root component from which a `LithoView` is created does not take any effect.

```
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    val frameLayout = FrameLayout(this)
    setContentView(frameLayout)
    val componentContext = ComponentContext(this)
    val component = Column.create(componentContext)
        .marginDip(YogaEdge.ALL, 32f)
        .backgroundColor(Color.RED)
        .child(
            Column.create(componentContext)
                .flexGrow(1f)
                .marginDip(YogaEdge.ALL, 16f)
                .backgroundColor(Color.GREEN)
                .build()
        )
        .build()
    val lithoView = LithoView.create(componentContext, component)
    frameLayout.addView(lithoView)
}
```

## Expected Behavior
The `32dp` margin should be visible

## Current Behavior
![image](https://user-images.githubusercontent.com/6842207/91029043-91469f80-e5fe-11ea-98fe-dab69b50633c.png)

**Comment by arpitratan** [comment]
Thank you @hipczor for reporting this. We are looking into it, we will update you once this is fixed.

**Comment by andrewpmsmith** [comment]
Litho can't add a margin to the root view as that is controlled by the ViewGroup that contains it.

Alternatives:
1. Use padding instead of margin.
2. If it needs to be margin (i.e. you want the FrameView's background to be visible around the edges of the LithoView) then you can apply the margin when adding the LayoutView to the FrameLayout
```
    LithoView lithoView = LithoView.create(c, component)
    FrameLayout.LayoutParams lp = new FrameLayout.LayoutParams(width, height);
    lp.setMargins(1, 2, 3, 4);
    frameLayout.addView(lithoView)
```

I'm working on a change to apply any margin on the root component as padding. However this could take a while as it breaks a lot of existing usages.
