### ISSUE TITLE
How to notify a MountSpec to remeasure it

### ISSUE THREAD

**Issue by mnayef95** [facebook/litho#725]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

I have a MountSpec like this:
```kotlin
@MountSpec
object AdMountSpec {

    @OnMeasure
    fun onMeasureLayout(
        c: ComponentContext?,
        layout: ComponentLayout?,
        widthSpec: Int,
        heightSpec: Int,
        size: Size?,
        @Prop adSize: AdSize
    ) {
        size?.width = SizeSpec.getSize(widthSpec)
        size?.height = (adSize.height + 10).dp
    }

    @OnCreateMountContent
    fun onCreateMountContent(context: Context?): AdView {
        return AdView(context)
    }

    @OnMount
    fun onMount(componentContext: ComponentContext, ad: AdView, @Prop adSize: AdSize) {
        banner.load(adSize)
        banner.onFailed { ad.visibility = View.GONE }
    }

    @OnUnmount
    fun onUnmount(c: ComponentContext?, ad: AdView) {
        ad.destroy()
    }
}
```

Now if you notice I have to hide the AdView if the loading failed, but I don't want to remove it from the list because I want it to reload when recycling, this code will hide the AdView but a white space will be visible instead because `onMeasureLayout` didn't call again.

How I can call it again to remeasure the view?

**Comment by arpitratan** [comment]
The ideal way to let framework know that remeasure has to be called is State Update. 
https://fblitho.com/docs/state#calling-state-updates

You can have post a state update to the layout spec which contains this MountSpec and pass this as a prop. The change in prop will ensure that the MountSpec is remeasured. 

Other hack which I can think of for this particular use case may be, is to add padding to AdView instead of increasing the size of the container in onMeasureLayout?
