### ISSUE TITLE
Support prop defaults being resource identifiers

### ISSUE THREAD

**Issue by emilsjolander** [facebook/litho#81]
Currently there is no way to specify the default value of a `ResType` prop using resource ids.

Say you declare a prop like the following
```java
@Prop(optional = true, resType = ResType.DIMEN_SIZE) int textSize
```

You would like to be able to declare its default value as being a dimension resource.
```java
@PropDefault protected static final int textSize = R.dimen.text_size_medium;
```

However that currently would not work as it would parse the resource id as an actual size value and not grab the size associated with the id.

This would most likely be solved by adding `resType` to the `@PropDefault` annotation.
```java
@PropDefault(resType = ResType.DIMEN_SIZE) protected static final int textSize = R.dimen.text_size_medium;
```

### Code pointers
https://github.com/facebook/litho/blob/master/litho-annotations/src/main/java/com/facebook/litho/annotations/Prop.java

https://github.com/facebook/litho/blob/master/litho-annotations/src/main/java/com/facebook/litho/annotations/PropDefault.java

https://github.com/facebook/litho/blob/master/litho-processor/src/main/java/com/facebook/litho/specmodels/generator/ComponentImplGenerator.java#L158

Point of contact: @emilsjolander

**Comment by pavlospt** [comment]
I have started working on this and my progress so far is: 
* I have added the ability to add a ResType on a PropDefault annotation.
* I extract it successfully and add it on the PropDefaultModel
* Parsing it correctly and initializing the Prop field with a proper initializer (only using the `resolveDimenSizeRes()` for now)

My thoughts on the above: 
* In order to use the resource resolve method, I tweaked the Component class to extend ResourceResolver and code generation works properly now. Although what this does is crash on Runtime because it does not have a valid ComponentContext to call `super.init(c, c.getResourceCache())`. 

I do not know if I am on the right path yet, but it seems to me that in order to support this we need to either extend ResourceResolver from Component and provide it with a valid ComponentContext or just initialize the PropDefault marked variable on the Builder where we have a valid ComponentContext.

Let me know what you think.

/cc: @emilsjolander @passy 

P.S.: Sorry for pinging here as well, might seem like spamming, but I want to save the time for anyone who would like to start working on this one and we end up having duplicate work.

**Comment by emilsjolander** [comment]
Could you publish your current progress as a pull request? This way we could make better suggestions based on the code. From the info you provided I think both alternatives would work. I see no reason not to pass the context down to the component.

**Comment by pavlospt** [comment]
@emilsjolander Ok will try to prepare a PR for them later in the day or tomorrow :)

**Comment by pavlospt** [comment]
Can be closed!
